### PR TITLE
CSS changes

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
This was more low hanging fruit that I figured I could help set up: some quick colors and fonts.

I added both of y'all to review since I don't know if y'all've already discussed the look and feel of things yet, and also aesthetics are subjective. :) 

I based everything off https://michiganlegalhelp.org/guide-to-legal-help, happy to edit or change anything later. I used the [ALDashboard bootstrap theme generator](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/customization/overview/#creating-a-custom-css-theme-with-bootstrapbuild), keeping most of the DA defaults except the primary color (which is now that MLH dark blue), the warning yellow (now a similar yellow from the MLH site) and the danger red (which is the red used in the above linked online form).

Since the logo was the same color as that MLH dark blue, I added a little white rounded background, kinda like an app button. Happy to change that too.

I also used the same fonts, with the same font size and line height. These will likely have to be changed, but I figured getting something in that's easily editable is better than trying to figure out where to change it later.

An image of what the SimpMotion looks like now with these styles:

Screenshot from 2023-10-10 18-43-58

### CODE REVIEW

**Review by normon66 — COMMENTED** [review]
Great idea and initiative. Overall, I like this. Not only does it tie it in with MLH branding, but it makes to logo pop and the overall page a little more spaced out and less crowded. 

My only potential concern/suggestion is the sizing of the `sections` headers, which could get a little lengthy with many of them wrapping to multiple lines. Then again, tools that have a large number of sections could override that sizing, if needed.

**Before:** 
image
 
**After:**
image

**Comment by BryceStevenWilley** [comment]
> My only potential concern/suggestion is the sizing of the sections headers

I think you bring up some good points. You're right that we can override all of these per interview, but I'm okay with shrinking the section names to be a bit smaller. I shrank them back down to their original size for now.

Screenshot of the navigation sidebar. Each of the labels "Tenant Information", "Rental Information", etc. now fit on one line each

**Comment by ekressmiller** [comment]
This is awesome, thanks Bryce!  I agree with shrinking the section headers.  My initial reaction is that the text of the subquestions might be a bit chunky/big too. (Which is honestly one of my pet peeves about our new website.)

I'll play around with it though and see how I feel over time.

I wonder how it would look if we replaced the blue indicator color on the section headers with the dark blue from the top?  It would pop less of course, but right now it stands out a little bit to me as an odd color combo.

**Comment by BryceStevenWilley** [comment]
> My initial reaction is that the text of the subquestions might be a bit chunky/big too.

Yeah, I think we can always revisit specific font sizes, it might take a while to get used to the new look since we've been developing on a more plain version for so long.

> I wonder how it would look if we replaced the blue indicator color on the section headers with the dark blue from the top? 

TBH I thought it was weird that it wasn't being replaced with our primary color, realized it was because of a docassemble bug. I fixed it, and much more is now the right color. New screenshot included.

Screenshot from 2023-10-12 11-38-52

It sounds like we're all on board with the idea, so I'll merge for now, and we can revisit some of the finer details later.

**Pull request merged**
