### PR TITLE
Aboutpagechanges

### PR DESCRIPTION
**Pull request by ekressmiller**
image

Here's what I'm thinking for the About page.  I left a lot of the info but tried to put it together into paragraphs to help with chunking the information. 

If you happen to see this and have immediate thoughts feel free to share! Otherwise I'll go ahead with merging and installing this around 1:00 Eastern and we can always iterate later.

### CODE REVIEW

**Comment by ekressmiller** [comment]
here's the current version for comparison:
image

**Comment by ekressmiller** [comment]
Actually I'm going to take lunch at 1:00 Eastern, so I'll probably be back and finish this up closer to 2:00 Eastern.  

I'll extend the testing deadline to the end of the day next Monday since this will go out later in the day.

**Comment by BryceStevenWilley** [comment]
I missed this, sorry! But it looks good to me!

**Comment by ekressmiller** [comment]
no worries it was very short notice!

**Pull request merged**
