### PR TITLE
Saving and navigation

### PR DESCRIPTION
**Pull request by ekressmiller**
Combine saving and navigation screens into one to reduce number of intro screens; and reduce word count throughout.

- Leaving the old version intact for now so that we don't break the live interview when we update.
- deleted custom header sizing we had added because it wasn't giving enough differentiation between header levels
- I also think the "Using this tool" name would now fit better for this screen, so I stole it and renamed MLH_intro_time.

### CODE REVIEW

**Review by normon66 — COMMENTED** [review]
Looks great! Just two things:

1. Because all of the `.da-subquestion hX` specifiers were removed from mlh_framework_theme.css, the `class="h5"` attributes can be removed from the `<h2>` tags in mlh_interview_framework.yml, correct? These appear in about 12 locations. 

2. On the new page, I think the three subheadings look a little better with a slightly smaller size to better differentiate them from the "Using this tool" header. For example, the image below uses `<h3>` for those subheadings instead of `<h2>`. Note that this solution would also benefit from a little more padding at the top of those `<h3>` tags, however. 

image

**Comment by ekressmiller** [comment]
@normon66 Unfortunately Docassemble does a weird thing with [header sizes](https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/coding_style_guide/accessibility#header-sizes), and the standard workaround is to manually change the header styles using that class= thing to adjust the size as needed. Shouldn't just change the header level itself for screen-reader accessibility reasons.

With the H5 class styling, I think it looks decent. (Note, this may not have shown up correctly for you during testing. I've been banging my head against the wall for the last 45 minutes trying to figure out what was happening and it turned out I needed a hard refresh to update the css.)
image

**Comment by normon66** [comment]
I figured something like that is why you were including the class attributes. I should have mentioned that in my earlier comment, the point of which was just to make note of the sizing. 

The class definitions were oddly not making any difference for me, even though I know I tried a Ctrl+F5 at one point.

All that said, I'm glad that the H5 approach is working correctly! Therefore, my original comments can be disregarded. Thanks!

**Comment by ekressmiller** [comment]
Yeah, the way the CSS was set up it was overriding any changes to the header class, and since the framework yml updated but the CSS didn't update without a hard refresh, it was very confusing to figure out what was happening!  Thanks for your comments as always!

**Pull request merged**
