### PR TITLE
Translate system phrases to avoid "register"

### LINKED ISSUE #60: Show password instructions when making an account
Likely an upstream fix, but could be something we can customize through docassemble, either by changing the rules, or by changing the login screen

Google doc comment link: ?disco=AAABDEjMkwQ

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
Prefering sign up as well, a bit simpler language.

With these config changes, fix #60:

```yml
words:
  - docassemble.mlhframework:data/sources/us-words.yml
  - docassemble.base...
...
register page heading: Sign up
register page title: Sign up
register page tab title: Sign up
register page submit: |
  Your password must be 6 characters long with 1 lowercase, 1 uppercase, and 1 number.
```

### CODE REVIEW

**Comment by ekressmiller** [comment]
looks good to me! I'll merge and make the config changes in both dev and prod.

**Comment by ekressmiller** [comment]
image
Looking good! This link still says "register" and I'm not sure how to figure out if there's a way to edit that. (I tried just adding it to that phrase to our us-words.yml but it did not seem to work.) Not a huge deal but just noting it in case there's an easy fix you're aware of @BryceStevenWilley

**Comment by ekressmiller** [comment]
Just noticed there's two versions of "New here? Register." in the docassemble base words file and one of them has two spaces in the middle instead of just one. I'll try again with two spaces and see if that makes a difference.

**Comment by ekressmiller** [comment]
it worked! disregard above

**Comment by BryceStevenWilley** [comment]
Good catch! That's fairly annoying, but unavoidable with how the translation system is designed. I'd leave both the phrases with one space and two spaces in there; I might remove that extra space upstream as there are language translations that don't seem to have the two spaces.

**Pull request merged**
